.TH GENISYS-INSTALL 1 "March 2024" "Version 1.0" "GENISYS Install Manual"
.SH NAME
genisys-install \- Install the configuration files
.SH SYNOPSIS
.B genisys install
[\-h] [\-\-file FILE] [\-\-root ROOT]
.SH DESCRIPTION
The
.B genisys install
command is used to install the configuration files.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display a help message and exit.
.TP
.B \-f FILE, \-\-file FILE
Specify input configuration file.
.TP
.B \-\-root ROOT
Specify the root directory for installation.
.SH SEE ALSO
.BR genisys (1)
.SH AUTHOR
Written by Rowan Akers, Benny Bergle, Robert Gingras and Henry Green.
.SH COPYRIGHT
Copyright (C) 2023-2024 Rowan Akers, Benny Bergle, Robert Gingras and Henry Green.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
Report any bugs to GitHub.

